name: Test
on:
  schedule:
    - cron: '1 0 * * *'
jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
      - run: gh api --method POST -H "Accept: application/vnd.github+json" /repos/trasparente/mdr/pages/builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}