name: Request_Pages_Build
on:
  schedule:
    - cron: '1 0 * * *'
jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
      - run: gh api -X POST repos/trasparente/mdr/pages/builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}